<?php

namespace App\Tests\TirePressureMonitoringSystem;

use App\TirePressureMonitoringSystem\Alarm;
use PHPUnit\Framework\TestCase;

class AlarmTest extends TestCase
{
    /** @var Alarm */
    protected $alarm;

    /** @var MockSensor */
    protected $sensor;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->sensor = new MockSensor();
        $this->alarm = new Alarm($this->sensor);
    }

    public function testCheck1()
    {
        $this->assertFalse($this->check(17));
        $this->assertFalse($this->check(21));
    }

    public function testCheck2()
    {
        $this->assertTrue($this->check(16));
        $this->assertTrue($this->check(19));
    }

    public function testCheck3()
    {
        $this->assertTrue($this->check(22));
        $this->assertTrue($this->check(19));
    }

    public function check(float $temp): bool
    {
        $this->sensor->setTemp($temp);
        $this->alarm->check();
        return $this->alarm->alarmOn();
    }
}
